### ISSUE TITLE
Decide what I am doing about the different languages and get the text translated as required

### ISSUE THREAD

**Issue by minnypatel** [cmharrison-astro/esoscienceambassadors#12]

**Comment by minnypatel** [comment]
There's probably a known design pattern for subbing content based on a language flag i.e. for the purpose of keeping the code clean

**Comment by minnypatel** [comment]
Also check out how good google's auto-translate is now, you *might* decide this is good enough? (Though I can totally understand arguments for multi-language, especially in your field).

**Comment by cmharrison-astro** [comment]
I think having the paragraphs of text stored in different files (for different languages) is probably the tidiest? I don't this Google translate is good enough for my colleagues who natively speak the different languages...

**Comment by minnypatel** [comment]
fair point,

something like this perhaps?

https://www.bitrepository.com/php-how-to-add-multi-language-support-to-a-website.html

**Comment by cmharrison-astro** [comment]
Exactly!

**Comment by cmharrison-astro** [comment]
Sorted following a similar method to described in that article.
