### ISSUE TITLE
Change db credentials

### ISSUE THREAD

**Issue by minnypatel** [cmharrison-astro/esoscienceambassadors#18]
The `config/db-config.php` file has been removed from the code, but is still discoverable as part of git history. Because of this the db credentials will need changing - the password and probably username as a minimum.

When the website is deployed it can be deployed with the new credentials, they just shouldn't be committed to github for the world to see.

We can discuss further if it's not clear.

**Comment by minnypatel** [comment]
I think we've got a little tangled up with the database credentials. It'd be good to find a time to talk (in realtime!) to get it sorted. It's not _mega_ urgent, but it'd be worth doing within a few days of starting to promote the site.

**Comment by cmharrison-astro** [comment]
We can chat tomorrow (Sunday) night if it works for you. Everything is working fine at my end and online now.

**Comment by cmharrison-astro** [comment]
In your phpMyAdmin under the eso_science_ambassadors database you will have set up users under "privileges" with a username and password. You should use these credentials, along with "localhost".
