### ISSUE TITLE
javascript issues in production

### ISSUE THREAD

**Issue by minnypatel** [cmharrison-astro/esoscienceambassadors#21]
I’ve been trying to migrate the website online for testing and have hit a problem with the javascript that I don’t understand. I ran babel locally and then uploaded the files in dist/ to the online server, but javascript errors are occurring....

http://biggesteyeonthesky.org

when you click on the menu you get this error:

![image](https://user-images.githubusercontent.com/6986623/45916890-fd458980-be64-11e8-9403-3c1fd420341f.png)

It looks like dropdown_menu.js is failing?

**Comment by minnypatel** [comment]
I've also got the problem that I can't scroll past this point in the page (i.e. the exoplanets dropdown menu), they *might* be related so it'd be best to fix the above first.

**Comment by minnypatel** [comment]
As everything works when running the project locally, either I'll need to:

1. make suggestions for you to try
2. get access to the hosting environment

...bare in mind I know very little about hosting / supporting live websites, as I'm used to working in big organisations where this is "someone else's job". That said...

**Comment by minnypatel** [comment]
### Idea 1

It's very suspicious that the first thing we can see failing is the last script that is loaded. I wonder if one of the previous scripts is breaking preventing us even _getting_ to `dropdown_menu.js`.
Note that other stuff may be failing, it's just that we can't see/invoke it yet.

1. Try re-ordering the scripts into the order you want them to load, but also put `dropdown_menu.js` first. Leave the orbit related stuff until last. This will help us see if one of the other scripts is in fact the broken one.
2. Try sticking the call to `dropdown_menu.js` at the top of the `<body>`. This will help us see whether the issue lies in the order the page is loading.
3. Then try invoking it as part of the `<head>` tag, *after the analytics stuff*. Quick example of syntax here: https://stackoverflow.com/questions/196702/where-to-place-javascript-in-an-html-file - This will load the js file before the rest of the page, and again will help us see whether the issue lies in the order the page is loading.

If this doesn't fix it and/or highlight a different problem, I'll have to get my thinking hat on.

**Comment by cmharrison-astro** [comment]
Okay,  based on your tests I have determined that the code is breaking at the first attempt to call php, it is not a javascript problem. Now to figure out why php is not working...

**Comment by cmharrison-astro** [comment]
Okay. So I forgot to upload db-connection.php...I'm a fool. For future reference though I found a very useful log file on the server side which enabled me to track down this problem.

**Comment by minnypatel** [comment]
Oh stuff like this happens all the time. That's what this emoji is for -> 🤦‍♂️
