### ISSUE TITLE
Credits box not displaying fully on phone

### ISSUE THREAD

**Issue by cmharrison-astro** [cmharrison-astro/esoscienceambassadors#22]
When I open the credits box on my phone it is not all displayed. Perhaps this current way of doing this is not the best...

**Comment by minnypatel** [comment]
Ah yeah, `alert()` has become the embarrassing uncle of javascript. I've not checked, but it probably just doesn't work on mobile browsers.

Either a Modal or and Overlay would probably work well - it's probably very similar to what I'm trying to do for the Privacy Policy and Cookies notice, so I might just change it at the same time.
